[DEV] Android Login UI 구성 및 Firebase Auth 연동
GDSC-CAU/Vridge-Android pull request #15
Opened 2024-01-26 19:34 UTC by yymin1022

## Summary
Android 애플리케이션에 LoginActivity UI를 구성하고 Firebase Auth를 연동하였습니다.

## Description
- LoginActivity의 View 및 VieWModel을 각각 생성하고 구성하였습니다.
- LoginView의 경우, 기본 Column 위젯으로 App Icon과 Google Sign-In Button을 렌더링합니다. 이 때, Google Sign-In Button은 Google Branding Guide에서 제공하는 이미지 형식을 활용해 구성하였습니다. App Icon은 기본 Android 리소스를 활용해 임시로 구성하여 지정하였습니다.
- LoginViewModel에서 Google Sign-In을 시작하는 로직을 처리하였습니다. 이 과정에서 `Context`가 필요한 부분을 Activity 메인 코드와 연동하여 구성하고자 Boolean 형식의 `LiveData`를 활용하였습니다. 또한, Activity 메인 코드에서 구성된 `ActivityResultLauncher`를 파라미터로 전달받아 Google Sign-In 로직 이후 연동해 호출하도록 하였습니다.
- Firebase Auth 객체에 접근하고 실제 Google Sign-In을 구성하는 로직은 별도의 `FirebaseAuthUtil` 싱글톤클래스(Object)에 작성하였습니다.
- LoginActivity의 `onCreate` 생명주기에서 Firebase Auth의 `getCurrentUser()`를 호출하도록 하여 자동로그인이 가능하도록 작성하였습니다.

좌 - Light / 우 - Dark
<div style="display: flex; flex-direction: row">
  <img width="45%" src="https://github.com/GDSC-CAU/Vridge-Android/assets/12806229/6a2988a7-1666-4ef4-a1db-820f198d2ce6" />
  <img width="45%" src="https://github.com/GDSC-CAU/Vridge-Android/assets/12806229/fa0f41ba-2d8e-4e00-add9-1cb006b3e489" />
</div>

P/S. MVVM 아키텍쳐를 제대로 활용한 것이 맞는지 모르겠읍니다.. 맘에안드는 부분이 있다면 탈탈 털어주십쇼 ㅎㅎ;
그리고 Dark모드 상태에서 NavigationBar 색상 정의를 추가해야할 것 같습니다?

2024-01-26 19:59 UTC, yymin1022 commented
Ktlint가 좀 많이 엄격한데요..
Composable 함수들을 죄다 소문자로 시작하라고 하는거랑 패키지명에 Underscore 넣지 말라고 하는건 비활성화하면 어떨까 싶습니다.

2024-01-27 07:31 UTC, ldh019 commented
컴포저블 소문자 시작은 오케바리로 하겠습니다만, 패키지는 underscore 대신 score를 쓰는게,, 아마 안드로이드 컨벤션이..지.. 싶은데..

2024-01-27 08:57 UTC, yymin1022 commented
변경된 Ktlint 적용까지 완료되었습니다!

2024-01-27 09:03 UTC, ldh019 requested changes
Screen 이름만 바꾸면 거의 뭐 GDE 저리가라 급;;

2024-01-27 09:03 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginActivity.kt
> +    private val viewModel: LoginViewModel by viewModels()
잘보고 따라했군요 아주 멋져요

2024-01-27 09:03 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginView.kt
> +fun LoginView(onTryLogin: () -> Unit) {
컴포즈에서는 화면을 Screen으로 많이 쓰긴 해요! 한번 잡솨보시는거 어떨까요 하하하

2024-01-27 09:03 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
> +@HiltViewModel
바람직하네 아주 멋져

2024-01-27 09:03 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
> +    ViewModel() {
이거 다 ktlint의 계략인건가

2024-01-27 09:03 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/utils/FirebaseAuthUtil.kt
> +object FirebaseAuthUtil {
솔직히 말해 당신 안드로이드 쌉고수지

2024-01-27 09:27 UTC, yymin1022 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginView.kt
> +fun LoginView(onTryLogin: () -> Unit) {
수정완료했습니다~

2024-01-27 09:27 UTC, yymin1022 commented on app/src/main/java/com/gdsc_cau/vridge/login/LoginViewModel.kt
> +    ViewModel() {
워닝뜨길래 띄어쓰기 넣어줬지..

2024-01-27 09:29 UTC, ldh019 approved these changes
LGTM!

2024-01-27 09:29 UTC, merged