[DEV] Repository 패턴 적용
GDSC-CAU/Vridge-Android pull request #34
Opened 2024-02-17 10:59 UTC by ldh019

## Summary
ViewModel에 연결될 data business logic 기초를 구현했습니다.

## Description
- 파일 구조 변경
- Repository, RepositoryImpl 클래스들 추가 및 구현
- API 클래스 추가 및 구현
- 관련 파일 DI 구현
- 파이어베이스, 레트로핏, Kotlin-Serialization, Json 의존성 추가
- 관련 Model 클래스 추가

2024-02-17 11:15 UTC, yymin1022 approved these changes
대량의 PR 잘 봤습니다!
API 선언부에서 Prefix가 통일되지 않은 부분만 추후 세부개발 과정에서 확인 부탁드립니다!

2024-02-17 11:15 UTC, yymin1022 commented on app/src/main/java/com/gdsc_cau/vridge/data/api/VridgeApi.kt
> +}
일부 API 함수에 `/` Prefix가 빠진 것은 의도한 것인가요?
아니라면 통일 부탁드립니다!

2024-02-17 11:20 UTC, yymin1022 requested changes
Merge Conflict가 발생하는데, Local 환경에서 Resovle가 필요하다고 하네요.
Rebase해서 다시 PR 부탁드립니다! :)

2024-02-18 03:42 UTC, ldh019 commented on app/src/main/java/com/gdsc_cau/vridge/data/api/VridgeApi.kt
> +}
감사합니다! 실수네요 ㅎㅎ 수정하겠습니다 :)

2024-02-18 07:54 UTC, yymin1022 approved these changes
그냥 GDE 들어가십쇼;; 기가막힌 아키텍쳐 코드 잘봤습니다!

2024-02-18 07:54 UTC, merged